# Generated by Django 4.2 on 2023-05-20 22:32

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobwebsite", "0002_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="image",
        ),
        migrations.AddField(
            model_name="profile",
            name="age",
            field=models.PositiveIntegerField(
                default=18,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.EmailField(default="", max_length=254),
        ),
        migrations.AddField(
            model_name="profile",
            name="first_name",
            field=models.CharField(default="", max_length=3000),
        ),
        migrations.AddField(
            model_name="profile",
            name="last_name",
            field=models.CharField(default="", max_length=3000),
        ),
        migrations.AddField(
            model_name="profile",
            name="username",
            field=models.CharField(default="", max_length=3000),
        ),
        migrations.AlterField(
            model_name="profile",
            name="birthdate",
            field=models.DateField(default=datetime.date(2023, 5, 20)),
        ),
    ]
