# Generated by Django 4.2 on 2023-05-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobwebsite", "0003_remove_profile_image_profile_age_profile_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(default="Cat03.jpg", upload_to="images"),
        ),
    ]
