# Generated by Django 4.2 on 2023-05-20 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobwebsite", "0004_profile_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="avatar",
        ),
    ]
