# Generated by Django 4.2 on 2023-06-04 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobwebsite", "0007_alter_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="birthdate",
            field=models.DateField(default=datetime.date(2023, 6, 4)),
        ),
    ]
