# Generated by Django 4.2.2 on 2023-06-18 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobwebsite', '0011_profile_favorites_alter_profile_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorites',
            field=models.CharField(default='{}', max_length=1000000),
        ),
    ]
