# Generated by Django 4.2.2 on 2023-06-21 01:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobwebsite', '0013_profile_favcount_alter_profile_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(default=datetime.date(2023, 6, 20)),
        ),
    ]
